name = "sveltekit-worker"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"
script_name = "do-worker"

[[migrations]]
tag = "v1"                        # Should be unique for each entry
new_classes = ["MyDurableObject"] # Array of new classes
