name = "sveltekit-worker-do"
compatibility_date = "2025-01-30"

build.command = "pnpm run build"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObjectLocal"

[[migrations]]
tag = "v1"                             # Should be unique for each entry
new_classes = ["MyDurableObjectLocal"] # Array of new classes
